name: speeds

services:
  # speed_laravel:
  #   image: speed_laravel
  #   depends_on:
  #     - mysql
  #     - redis
  #   volumes:
  #     - ./:/opt/www

  hyperf:
    image: speed_hyperf
    ports:
      - 8001:8001
    depends_on:
      - mysql
      - redis
    volumes:
      - ./:/opt/www

  # nginx:
  #   image: nginx:1.27.3-alpine-perl
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - ./laravel/speed_laravel.conf:/etc/nginx/conf.d/speed_laravel.conf

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: speeds
      MYSQL_USER: speed
      MYSQL_PASSWORD: zZ1853212
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7.4-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
networks:
  speed_network:
    driver: bridge
