#!/usr/bin/env php
<?php
# 关闭端口
foreach ([8001] as $port) {
    $cmd = "lsof -i tcp:$port -t | xargs kill -9";
    $output = shell_exec($cmd);
    if ($output === null) {
        echo "Port $port has been killed \n";
    } else {
        echo "Output: " . $output . "\n";
    }
}